### ISSUE TITLE
같은 알고리즘이 있습니다.

### ISSUE THREAD

**Issue by jihoonahn** [joog-lim/Bamboo-APIv3#20]
<img width="653" alt="스크린샷 2022-04-18 오후 7 53 40" src="https://user-images.githubusercontent.com/68891494/163798630-e75e5998-a5f0-43a8-abb4-b9b6dd469862.png">

알고리즘번호가 같은 알고리즘이 있습니다.
수정 부탁 드립니다.

**Comment by sunrabbit123** [comment]
Clear!
