### ISSUE TITLE
좋아요가 추가가 안됩니다

### ISSUE THREAD

**Issue by kimsh153** [joog-lim/Bamboo-APIv3#21]
<img width="685" alt="스크린샷 2022-04-18 오후 8 20 24" src="https://user-images.githubusercontent.com/81547954/163801109-41e63c83-3233-40ae-be8b-009f9ec8dadf.png">
좋아요 누르고
<img width="707" alt="스크린샷 2022-04-18 오후 8 20 32" src="https://user-images.githubusercontent.com/81547954/163801114-da96529f-e90b-41eb-aa14-535ef9a4e857.png">
다시 새로고침하면 좋아요가 사라져요
<img width="692" alt="스크린샷 2022-04-18 오후 8 20 57" src="https://user-images.githubusercontent.com/81547954/163801160-b8b0492e-0759-4210-a1c5-601d15391ab7.png">

**Comment by sunrabbit123** [comment]
프론트엔드 문제로 판단됩니다.

https://github.com/joog-lim/bamboo-front/issues

해당 위치에서 이슈 부탁드려요
